# Generated by Django 5.1.6 on 2025-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
