# Generated by Django 5.1.6 on 2025-03-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutus',
            new_name='Aboutme',
        ),
    ]
