# Generated by Django 5.1.6 on 2025-03-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
