# Generated by Django 5.1.6 on 2025-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
